//CONSULTA PARA INSERTAR LOS DATOS DE LA TABLA ALUMNO A LA TABLA alumno_horizontal
INSERT INTO alumno_horizontal1 SELECT * FROM alumno WHERE codigo BETWEEN 1 AND 2000000;
 
//CONSULTA PARA INSERTAR DATOS DE LA TABLA alumno A alumno_horizontal2
INSERT INTO alumno_horizontal2 SELECT * FROM alumno WHERE codigo BETWEEN 2000001 AND 4000000;